ThinkPower.CCLPA.Web/ViewModels/PreAdjustImportViewModel.cs
namespace ThinkPower.CCLPA.Web.ViewModels
{
    /// <summary>
    /// 匯入臨調預審名單檢視模型類別
    /// </summary>
    public class PreAdjustImportViewModel
    {
        /// <summary>
        /// 行銷活動代碼
        /// </summary>
        public string CampaignId { get; set; }

        /// <summary>
        /// 是否執行匯入
        /// </summary>
        public bool ExecuteImport { get; set; }

        /// <summary>
        /// 錯誤訊息
        /// </summary>
        public string ErrorMessage { get; set; }

        /// <summary>
        /// 臨調預審名單數量
        /// </summary>
        public int? CampaignDetailCount { get; set; }

    }
}

ThinkPower.CCLPA.Web/Controllers/AdjustController.cs
using NLog;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using ThinkPower.CCLPA.Domain.Entity;
using ThinkPower.CCLPA.Domain.Service;
using ThinkPower.CCLPA.Domain.VO;
using ThinkPower.CCLPA.Web.ActionModels;
using ThinkPower.CCLPA.Web.Models;
using ThinkPower.CCLPA.Web.ViewModels;

namespace ThinkPower.CCLPA.Web.Controllers
{
    /// <summary>
    /// 專案臨調
    /// </summary>
    public class AdjustController : BaseController
    {
        #region Private PropertyOrField

        #endregion



        #region Action Method

        /// <summary>
        /// 預設首頁
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            AdjustProcessViewModel viewModel = InitialAdjustProcessViewModel();

            return View(_adjustProcessPage, viewModel);
        }

        /// <summary>
        /// 查詢歸戶ID
        /// </summary>
        /// <param name="actionModel">來源資料</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Query(AdjustQueryActionModel actionModel)
        {
            AdjustVerifyResult adjustVerifyResult = null;

            try
            {
                if (!Request.IsAjaxRequest())
                {
                    throw new InvalidOperationException("Not AjaxRequest");
                }
                else if (actionModel == null)
                {
                    throw new ArgumentNullException(nameof(actionModel));
                }

                adjustVerifyResult = AdjService.Verify(actionModel.CustomerId);
            }
            catch (Exception e)
            {
                logger.Error(e);
            }

            return Json(adjustVerifyResult, "application/json", Encoding.UTF8);
        }

        /// <summary>
        /// 取得臨調申請資料
        /// </summary>
        /// <param name="actionModel">來源資料</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetApplicationData(AdjustApplicationActionModel actionModel)
        {
            AdjustProcessViewModel viewModel = InitialAdjustProcessViewModel();

            try
            {
                if (actionModel == null)
                {
                    throw new ArgumentNullException(nameof(actionModel));
                }

                AdjustApplication application = AdjService.GetApplicationData(actionModel.CustomerId);

                Customer customer = application.Customer;

                viewModel.CustomerId = actionModel.CustomerId;

                viewModel.JcicQueryDate = application.JcicSendQuery.JcicQueryDate;

                viewModel.ProjectAdjustResult = application?.AdjustValidateResult?.ProjectResult;
                viewModel.ProjectRejectReason = application?.AdjustValidateResult?.ProjectRejectReason;
                viewModel.GeneralAdjustResult = application?.AdjustValidateResult?.EstimateResult;
                viewModel.GeneralRejectReason = application?.AdjustValidateResult?.RejectReason;


                viewModel.Vip = new AdjustProcessVip() { MonthStarLevel = application?.Vip?.MonthStarLevel };

                viewModel.Customer = new AdjustProcessCustomer
                {
                    AccountId = customer.AccountId,
                    LiveCardCount = ((customer.LiveCardCount == null) || (customer.LiveCardCount <= 0)) ? "N" : "Y",
                    Status = customer.Status,
                    DataDate = customer.DataDate,
                    ChineseName = customer.ChineseName,
                    BirthDay = customer.BirthDay,
                    AboutDataStatus = customer.AboutDataStatus,
                    RiskLevel = customer.RiskLevel,
                    RiskRating = customer.RiskRating,
                    IssueDate = customer.IssueDate,
                    ClosingDay = customer.ClosingDay,
                    PayDeadline = customer.PayDeadline,
                    Vocation = customer.Vocation,
                    TelHome = customer.TelHome,
                    TelOffice = customer.TelOffice,
                    MobileTel = customer.MobileTel,
                    BillAddr = customer.BillAddr,
                    SystemAdjustRevFlag = customer.SystemAdjustRevFlag,
                    CreditLimit = customer.CreditLimit,
                    ClosingAmount = customer.ClosingAmount,
                    MinimumAmountPayable = customer.MinimumAmountPayable,
                    RecentPaymentDate = customer.RecentPaymentDate,
                    RecentPaymentAmount = customer.RecentPaymentAmount,
                    OfferAmount = customer.OfferAmount,
                    UnpaidTotal = customer.UnpaidTotal,
                    AuthorizedAmountNotAccount = customer.AuthorizedAmountNotAccount,
                    CcasUnderpaidAmount = customer.CcasUnderpaidAmount,
                    CcasUsabilityAmount = customer.CcasUsabilityAmount,
                    CcasUnderpaidRate = customer.CcasUnderpaidRate,
                };

                viewModel.AdjustLog = new AdjustLogModel
                {

                    AdjustReason = customer.AdjustReason,
                    AdjustArea = customer.AdjustArea,
                    AdjustStartDate = customer.AdjustStartDate,
                    AdjustEndDate = customer.AdjustEndDate,
                    AdjustEffectAmount = customer.AdjustEffectAmount,
                    AdjustLogList = application.AdjustLogList,
                };

                viewModel.NearlyYearRating = new NearlyYearRatingModel()
                {
                    LatestMnthList = new AdjustProcessLatestMnth[] {
                            new AdjustProcessLatestMnth(){ Month =1  , Rating = customer.Latest1Mnth },
                            new AdjustProcessLatestMnth(){ Month =2  , Rating = customer.Latest2Mnth },
                            new AdjustProcessLatestMnth(){ Month =3  , Rating = customer.Latest3Mnth },
                            new AdjustProcessLatestMnth(){ Month =4  , Rating = customer.Latest4Mnth },
                            new AdjustProcessLatestMnth(){ Month =5  , Rating = customer.Latest5Mnth },
                            new AdjustProcessLatestMnth(){ Month =6  , Rating = customer.Latest6Mnth },
                            new AdjustProcessLatestMnth(){ Month =7  , Rating = customer.Latest7Mnth },
                            new AdjustProcessLatestMnth(){ Month =8  , Rating = customer.Latest8Mnth },
                            new AdjustProcessLatestMnth(){ Month =9  , Rating = customer.Latest9Mnth },
                            new AdjustProcessLatestMnth(){ Month =10 , Rating = customer.Latest10Mnth },
                            new AdjustProcessLatestMnth(){ Month =11 , Rating = customer.Latest11Mnth },
                            new AdjustProcessLatestMnth(){ Month =12 , Rating = customer.Latest12Mnth },
                        },
                    ConsumeList = new AdjustProcessConsume[] {
                            new AdjustProcessConsume(){ Month =1  , Amount = customer.Consume1  },
                            new AdjustProcessConsume(){ Month =2  , Amount = customer.Consume2  },
                            new AdjustProcessConsume(){ Month =3  , Amount = customer.Consume3  },
                            new AdjustProcessConsume(){ Month =4  , Amount = customer.Consume4  },
                            new AdjustProcessConsume(){ Month =5  , Amount = customer.Consume5  },
                            new AdjustProcessConsume(){ Month =6  , Amount = customer.Consume6  },
                            new AdjustProcessConsume(){ Month =7  , Amount = customer.Consume7  },
                            new AdjustProcessConsume(){ Month =8  , Amount = customer.Consume8  },
                            new AdjustProcessConsume(){ Month =9  , Amount = customer.Consume9  },
                            new AdjustProcessConsume(){ Month =10 , Amount = customer.Consume10 },
                            new AdjustProcessConsume(){ Month =11 , Amount = customer.Consume11 },
                            new AdjustProcessConsume(){ Month =12 , Amount = customer.Consume12 },
                        },
                    PreCashList = new AdjustProcessPreCash[] {
                            new AdjustProcessPreCash(){ Month =1  , Amount = customer.PreCash1  },
                            new AdjustProcessPreCash(){ Month =2  , Amount = customer.PreCash2  },
                            new AdjustProcessPreCash(){ Month =3  , Amount = customer.PreCash3  },
                            new AdjustProcessPreCash(){ Month =4  , Amount = customer.PreCash4  },
                            new AdjustProcessPreCash(){ Month =5  , Amount = customer.PreCash5  },
                            new AdjustProcessPreCash(){ Month =6  , Amount = customer.PreCash6  },
                            new AdjustProcessPreCash(){ Month =7  , Amount = customer.PreCash7  },
                            new AdjustProcessPreCash(){ Month =8  , Amount = customer.PreCash8  },
                            new AdjustProcessPreCash(){ Month =9  , Amount = customer.PreCash9  },
                            new AdjustProcessPreCash(){ Month =10 , Amount = customer.PreCash10 },
                            new AdjustProcessPreCash(){ Month =11 , Amount = customer.PreCash11 },
                            new AdjustProcessPreCash(){ Month =12 , Amount = customer.PreCash12 },
                        },
                    CreditRatingList = new AdjustProcessCreditRating[] {
                            new AdjustProcessCreditRating(){ Month =1  , Rating = customer.CreditRating1  },
                            new AdjustProcessCreditRating(){ Month =2  , Rating = customer.CreditRating2  },
                            new AdjustProcessCreditRating(){ Month =3  , Rating = customer.CreditRating3  },

ThinkPower.CCLPA.Web/Views/Adjust/PreAdjustImport.cshtml
@model ThinkPower.CCLPA.Web.ViewModels.PreAdjustImportViewModel

@{
    ViewBag.Title = "專案臨調預審名單匯入";
}


<div class="row">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
</div>





@using (Html.BeginForm("PreAdjustValidate", "Adjust", FormMethod.Get))
{
    <div class="row">
        <div class="col col-auto">
            <span>ILRC行銷活動編碼</span>
        </div>

        <div class="col col-auto">
            @Html.TextBox("CampaignId", null, new { @class = "form-control" })
        </div>

        <div class="col col-auto">
            <input type="submit" value="名單匯入" class="btn btn-success" />
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col col-auto text-danger">
            <span>說明：請先於ILRC提案，上雙向簡訊、預審名單</span>
        </div>
    </div>
}





<div class="row">

    @if (Model != null)
    {
        string tipTitle = null;
        string tipMessage = null;
        bool executeImport = false;

        if (Model.ExecuteImport)
        {
            tipTitle = "提示訊息";
            tipMessage = "名單匯入完成";
        }
        else if (!String.IsNullOrEmpty(Model.ErrorMessage))
        {
            tipTitle = "檢核錯誤提示訊息";
            tipMessage = Model.ErrorMessage;
        }
        else if (String.IsNullOrEmpty(Model.ErrorMessage))
        {
            if (Model.CampaignDetailCount > 0)
            {
                tipTitle = "提示訊息";
                tipMessage = $"您確定要將行銷活動編號「{Model.CampaignId}」合計{Model.CampaignDetailCount}筆資料，進行匯入作業嗎?";
                executeImport = true;
            }
            else
            {
                tipTitle = "檢核提示訊息";
                tipMessage = "行銷活動編號已失效或無可匯入名單。";
            }
        }

        <div class="modal" tabindex="-1" role="dialog" id="tip-modal">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">@tipTitle</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>@tipMessage</p>
                    </div>
                    <div class="modal-footer">
                        @if (Model.ExecuteImport)
                        {
                            @Html.ActionLink("確定", "PreAdjustImportPage", "Adjust", new { }, new { @class = "btn btn-primary" })
                        }
                        else if (executeImport)
                        {
                            @Html.ActionLink("確定", "PreAdjustImport", "Adjust", new { CampaignId = Model.CampaignId, ExecuteImport = executeImport }, new { @class = "btn btn-primary" })
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">取消</button>
                        }
                        else
                        {
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">確定</button>
                        }
                    </div>
                </div>
            </div>
        </div>
    }

</div>





@section scripts{
    <script src="~/Scripts/PreAdjustImport.js"></script>
}

ThinkPower.CCLPA.Web/Views/Adjust/PreAdjustProcess.cshtml
@model ThinkPower.CCLPA.Web.ViewModels.PreAdjustProcessViewModel
@using PagedList.Mvc;

@{
    ViewBag.Title = "專案臨調預審名單處理";

    var canExecuteOperation = (Model != null && Model.CanExecuteOperation == true) ? true : false;
    var customerId = (Model == null) ? null : Model.CustomerId;
}

<span>專案臨調預審名單處理</span>


<hr />
@using (Html.BeginForm("PreAdjustLoad", "Adjust", FormMethod.Get, new { id = "form-query" }))
{
    <div class="row">
        <div class="col col-auto">
            <span>身分證字號</span>
        </div>

        <div class="col col-auto">
            @Html.TextBox("CustomerId", customerId, new { @class = "form-control", maxlength="10" })
        </div>

        <div class="col col-auto">
            <input type="button" name="query-pre-adjust" id="query-pre-adjust" value="查詢" class="btn btn-primary" />
        </div>
    </div>

    <br />
    <div class="row d-none">
        <div class="col col-auto">
            <span>等待區頁數</span>
        </div>

        <div class="col col-auto">
            @Html.TextBox("NotEffectPageIndex", Model.NotEffectPageIndex, new { @class = "form-control" })
        </div>

        <div class="col col-auto">
            <span>生效區頁數</span>
        </div>

        <div class="col col-auto">
            @Html.TextBox("EffectPageIndex", Model.EffectPageIndex, new { @class = "form-control" })
        </div>
    </div>
}





<hr />
<div class="row process-options">
    <div class="col col-auto process-remark">
        <span>備註</span>
    </div>

    <div class="col col-auto">
        @Html.TextBox("not-effect-remark", null, new { @class = "form-control" })
    </div>

    @if (canExecuteOperation)
    {
        <div class="col col-auto">
            <input type="button" name="name" id="delete-not-effect" value="刪除等待區" class="btn btn-danger" />
        </div>
        <div class="col col-auto">
            <input type="button" name="name" id="force-agree" value="強制同意" class="btn btn-success" />
        </div>
        <div class="col col-auto">
            <input type="button" name="name" id="agree" value="同意執行" class="btn btn-primary" />
        </div>
    }
    else
    {
        <div class="col col-auto">
            <input type="button" name="name" id="delete-not-effect" value="刪除等待區" class="btn btn-danger disabled" />
        </div>
        <div class="col col-auto">
            <input type="button" name="name" id="force-agree" value="強制同意" class="btn btn-success disabled" />
        </div>
        <div class="col col-auto">
            <input type="button" name="name" id="agree" value="同意執行" class="btn btn-primary disabled" />
        </div>
    }
</div>

<br />

<div class="row">
    <div class="table-responsive">
        <table class="table table-hover table-striped" style="width:80%;" id="process-table-not-effect">
            <thead class="thead-light">
                <tr class="text-center">
                    <th scope="col">功能</th>
                    <th scope="col">匯入日期</th>
                    <th scope="col">預審專案</th>
                    <th scope="col">ID</th>
                    <th scope="col">姓名</th>
                    <th scope="col">預審金額</th>
                    <th scope="col">截止日</th>
                    <th scope="col">客戶類型</th>
                    <th scope="col">簡訊比對</th>
                    <th scope="col">狀態</th>
                    <th scope="col">處理日期時間</th>
                    <th scope="col">同意人員</th>
                    <th scope="col">刪除人員</th>
                    <th scope="col">刪除日期時間</th>
                    <th scope="col">備註</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null && Model.NotEffectPreAdjustList != null)
                {
                    foreach (var preAdjust in Model.NotEffectPreAdjustList.Where(x => x.CcasReplyCode != "00"))
                    {
                        <tr data-campaign-id="@preAdjust.CampaignId"
                            data-customer-id="@preAdjust.CustomerId"
                            data-status="@preAdjust.Status">
                            <th scope="row">
                                <input type="checkbox" name="name" id="pre-adjust-check-box" value="" />
                            </th>
                            <td>@Html.DisplayFor(x => preAdjust.ImportDate)</td>
                            <td>@Html.DisplayFor(x => preAdjust.ProjectName)</td>
                            <td>@Html.DisplayFor(x => preAdjust.CustomerId)</td>
                            <td>@Html.DisplayFor(x => preAdjust.ChineseName)</td>
                            <td>@Html.DisplayFor(x => preAdjust.ProjectAmount)</td>
                            <td>@Html.DisplayFor(x => preAdjust.CloseDate)</td>
                            <td>@Html.DisplayFor(x => preAdjust.Kind)</td>
                            <td>@Html.DisplayFor(x => preAdjust.SmsCheckResult)</td>
                            <td>@Html.DisplayFor(x => preAdjust.Status)</td>
                            <td>@Html.DisplayFor(x => preAdjust.ProcessingDateTime)</td>
                            <td>@Html.DisplayFor(x => preAdjust.ProcessingUserId)</td>
                            <td>@Html.DisplayFor(x => preAdjust.DeleteUserId)</td>
                            <td>@Html.DisplayFor(x => preAdjust.DeleteDateTime)</td>
                            <td>@Html.DisplayFor(x => preAdjust.Remark)</td>
                        </tr>
                    }
                }
            </tbody>
        </table>
        @if (Model != null && Model.NotEffectPreAdjustList != null)
        {
            @Html.PagedListPager(Model.NotEffectPreAdjustList, page => $"?{page},NotEffect")
        }
    </div>
</div>







<hr />
<div class="row process-options">
    <div class="col col-auto process-remark">
        <span>備註</span>
    </div>

    <div class="col col-auto">
        @Html.TextBox("effect-remark", null, new { @class = "form-control" })
    </div>

    @if (canExecuteOperation)
    {
        <div class="col col-auto">
            <input type="button" name="name" id="delete-effect" value="刪除生效區" class="btn btn-danger" />
        </div>
    }
    else
    {
        <div class="col col-auto">
            <input type="button" name="name" id="delete-effect" value="刪除生效區" class="btn btn-danger disabled" />
        </div>
    }
</div>

<br />

<div class="row">
    <div class="table-responsive">
        <table class="table table-hover table-striped" style="width:80%;" id="process-table-effect">
            <thead class="thead-light">
                <tr class="text-center">
                    <th scope="col">功能</th>
                    <th scope="col">匯入日期</th>
                    <th scope="col">預審專案</th>
                    <th scope="col">ID</th>
                    <th scope="col">姓名</th>
                    <th scope="col">預審金額</th>
                    <th scope="col">截止日</th>
                    <th scope="col">客戶類型</th>
                    <th scope="col">簡訊比對</th>
                    <th scope="col">狀態</th>
                    <th scope="col">處理日期時間</th>
                    <th scope="col">同意人員</th>
                    <th scope="col">強制人員</th>
                    <th scope="col">刪除人員</th>
                    <th scope="col">刪除日期時間</th>
                    <th scope="col">備註</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null && Model.EffectPreAdjustList != null)
                {
                    foreach (var preAdjust in Model.EffectPreAdjustList.Where(x => x.CcasReplyCode == "00"))
                    {
                        <tr data-campaign-id="@preAdjust.CampaignId"
                            data-customer-id="@preAdjust.CustomerId"
                            data-status="@preAdjust.Status">
                            <th scope="row">
                                <input type="checkbox" name="name" id="pre-adjust-check-box" value="" />
                            </th>
                            <td>@Html.DisplayFor(x => preAdjust.ImportDate)</td>
                            <td>@Html.DisplayFor(x => preAdjust.ProjectName)</td>
                            <td>@Html.DisplayFor(x => preAdjust.CustomerId)</td>
                            <td>@Html.DisplayFor(x => preAdjust.ChineseName)</td>
                            <td>@Html.DisplayFor(x => preAdjust.ProjectAmount)</td>
                            <td>@Html.DisplayFor(x => preAdjust.CloseDate)</td>
                            <td>@Html.DisplayFor(x => preAdjust.Kind)</td>
                            <td>@Html.DisplayFor(x => preAdjust.SmsCheckResult)</td>
                            <td>@Html.DisplayFor(x => preAdjust.Status)</td>
                            <td>@Html.DisplayFor(x => preAdjust.ProcessingDateTime)</td>
                            <td>@Html.DisplayFor(x => preAdjust.ProcessingUserId)</td>
                            <td>@Html.DisplayFor(x => preAdjust.ForceAgreeUserId)</td>
                            <td>@Html.DisplayFor(x => preAdjust.DeleteUserId)</td>
                            <td>@Html.DisplayFor(x => preAdjust.DeleteDateTime)</td>
                            <td>@Html.DisplayFor(x => preAdjust.Remark)</td>
                        </tr>
                    }
                }
            </tbody>
        </table>
        @if (Model != null && Model.EffectPreAdjustList != null)
        {
            @Html.PagedListPager(Model.EffectPreAdjustList, page => $"?{page},Effect")
        }
    </div>
</div>





<hr />
<div class="row">

    @if (Model != null)
    {
        string tipTitle = null;
        string tipMessage = null;

        if (!String.IsNullOrEmpty(Model.ErrorMessage))
        {
            tipTitle = "錯誤訊息";
            tipMessage = Model.ErrorMessage;
        }
        else if (!String.IsNullOrEmpty(Model.TipMessage))
        {
            tipTitle = "錯誤訊息";
            tipMessage = Model.TipMessage;
        }
        else if (
            (Model.NotEffectPreAdjustList == null || !Model.NotEffectPreAdjustList.Any()) &&
            (Model.EffectPreAdjustList == null || !Model.EffectPreAdjustList.Any())
            )
        {
            tipTitle = "提示訊息";
            tipMessage = "查無相關資料，請確認是否有輸入錯誤。";
        }

        <div class="modal" tabindex="-1" role="dialog" id="tip-modal">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">@tipTitle</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>@tipMessage</p>
                    </div>
                    <div class="modal-footer">
                        <div id="tip-modal-type-show">
                            <button type="button" class="btn btn-primary" data-dismiss="modal">確認</button>
                        </div>
                        <div id="tip-modal-type-dialog">
                            <button type="button" class="btn btn-primary" id="tip-model-confirm">確定</button>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">取消</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }

</div>


@section scripts{
    <script src="~/Scripts/PreAdjustProcess.js"></script>
}

ThinkPower.CCLPA.Web/Views/Adjust/ValidatePreAdjust.cshtml
@model ThinkPower.CCLPA.Web.ViewModels.ValidatePreAdjustViewModel

@{
    ViewBag.Title = "ValidatePreAdjust";

    var validateInfo = (Model == null) || (Model.ValidatePreAdjustResult == null) ? null :
        Model.ValidatePreAdjustResult;

}


<div class="row">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
</div>

@using (Html.BeginForm("ValidatePreAdjust", "Adjust", FormMethod.Get))
{
    <div class="row">
        <div class="col col-auto">
            <span>ILRC行銷活動編碼</span>
        </div>

        <div class="col col-auto">
            @Html.TextBox("CampaignId", null, new { @class = "form-control" })
        </div>

        <div class="col col-auto">
            <input type="submit" value="名單匯入" class="btn btn-success" />
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col col-auto text-danger">
            <span>說明：請先於ILRC提案，上雙向簡訊、預審名單</span>
        </div>
    </div>
}

<div class="row">

    @if (validateInfo != null)
    {
        var title = String.Empty;
        var msg = String.Empty;
        var importFlag = false;

        if (!String.IsNullOrEmpty(validateInfo.ErrorMessage))
        {
            title = "檢核錯誤提示訊息";
            msg = validateInfo.ErrorMessage;
        }
        else if (String.IsNullOrEmpty(validateInfo.ErrorMessage))
        {
            if (validateInfo.CampaignListCount > 0)
            {
                title = "提示訊息";
                msg = $"您確定要將行銷活動編號「{Model.CampaignId}」合計{validateInfo.CampaignListCount}筆資料，進行匯入作業嗎?";
                importFlag = true;
            }
            else
            {
                title = "檢核提示訊息";
                msg = "行銷活動編號已失效或無可匯入名單。";
            }
        }

        <div class="modal" tabindex="-1" role="dialog" id="tip-modal">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">@title</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>@msg</p>
                    </div>
                    <div class="modal-footer">
                        @if (importFlag)
                        {
                            @Html.ActionLink("確定", "ImportPreAdjust", "Adjust",new { CampaignId = Model.CampaignId },new { @class = "btn btn-primary" })
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">取消</button>
                        }
                        else
                        {
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">確定</button>
                        }
                    </div>
                </div>
            </div>
        </div>
    }

</div>



@section scripts{
    <script>

        if ($('#tip-modal').length > 0) {
            $('#tip-modal').modal('show');
        }

    </script>
}